server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:h2:mem:bibliotecadb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update